name: Sync to Hugging Face hub
on:
  push:
    branches: [Master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug info
        run: |
          echo "Current branch: $GITHUB_REF_NAME"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Pushing to Hugging Face..."
          git push --force https://WHITETITAN:$HF_TOKEN@huggingface.co/spaces/WHITETITAN/multiAgent-pipeline Master:main